### ISSUE TITLE
Response is almost never received

### ISSUE THREAD

**Issue by adeebshihadeh** [jacksonliam/Smoothie8266#1]
I hardcoded a delay so that the machine has time to respond, but a hardcoded delay is not ideal since some commands won't need that whole time which will just slow down communication or responses will be cutoff after the delay is over.

**Comment by jacksonliam** [comment]
Thanks for trying this out! 
On my local branch I've put in a loop to wait until there's some serial data, with a timeout if none received. I'll push that once I'm at my PC. 

But mainly I'm working on the esphttpd version when I get a minute! 

However, the tricky part is actually making sure we're at the end of the stream once we stop reading, smoothie doesn't output any 'end of message' marker and the messages can be multiline. 

Right now I assume smoothie can fill the buffer faster than the ESP can read it...

**Comment by adeebshihadeh** [comment]
I think for now I'll make a list of gcode and expected response patterns and have it wait until it sees that pattern, so I can start using fabrica on my azteeg x5s.
